### PR TITLE
Bump version to 1.4.18 for jboss-amq

### PR DESCRIPTION
**Pull request by kwoodson**
Bumping version to 1.4.18 from 1.4.12.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

Is there a critical bugfix in the amq version bump?

**Comment by adambkaplan** [comment]
@kwoodson we inadvertently merged this PR, and subsequently will revert ti in #163.

We are freezing openshift/library until 4.0 GA, with exceptions for critical bugfixes.

**Comment by kwoodson** [comment]
@adambkaplan

This is causing us a small bit of grief. The latest version has been out since October and the official version of the EAP version in the official.yaml is already at  .18. This brings jboss amq in line with EAP.

When does this branch open?

**Comment by adambkaplan** [comment]
Branch will be open latest after GA. I need to verify if we can open after code freeze (May 9th).

**Comment by bparees** [comment]
@adambkaplan depending on what @kwoodson needs (ie if they need these changes in library because they pull from there, but they do not need the changes in the samples operator because they don't use it), it may be time to consider @gabemontero's suggestion of introducing branches in this repo and having the samples operator pull from branches (or tags).

This repo isn't intended to be solely controlled by the samples operator, it's a generic publishing location for content with consumers(samples operator, starter, etc) picking what they want from it.  So we can't hold up publishing for everyone because of the 4.1 release cycle.

**Comment by gabemontero** [comment]
On Fri, Apr 26, 2019 at 8:50 AM Ben Parees <notifications@github.com> wrote:

> @adambkaplan <https://github.com/adambkaplan> depending on what @kwoodson
> <https://github.com/kwoodson> needs (ie if they need these changes in
> library because they pull from there, but they do not need the changes in
> the samples operator because they don't use it), it may be time to consider
> @gabemontero <https://github.com/gabemontero>'s suggestion of introducing
> branches in this repo and having the samples operator pull from branches
> (or tags).
>
Presumably the code at
https://github.com/openshift/cluster-samples-operator/blob/master/tmp/build/library-sync.sh#L7
can be tweaked to reference
a non-master branch/tag.

**Comment by adambkaplan** [comment]
@gabemontero yes it can - tested this out myself on one of the revert branches.

**Pull request merged**
