### PR TITLE
Add build template for OpenJDK to IBM Semeru transition

### PR DESCRIPTION
**Pull request by dale-fu**
Initial PR to add generic template to convert OpenJDK 11 to IBM Semeru 11.

### CODE REVIEW

**Comment by fbm3307** [comment]
@dale-fu  can you shed some more light onto this for us to understand better , as to why this is required

**Comment by levivic** [comment]
hi @fbm3307, the template is needed for potential customers to switch their JVM choice of certain RH openshift products which are based on Java, such as EAP, RHSSO .... Details can be found in https://access.redhat.com/articles/6744521. This template should be part of the last section of the article, `Transitioning back to OpenJ9`.  After some discussion with affected products teams, we agree to use openshift/library to host the template.

**Comment by fbm3307** [comment]
@dale-fu @levivic 
I would like to suggest that instead of creating templates in openshift/library, you can create helm charts for the same (See here https://github.com/openshift-helm-charts/charts )
It is easier to create helm charts and also the helm charts would be available across ocp version 4.8 to latest 4.11. In this you will not have to worry about backporting or waiting for the release, also no worries on checking if compatible with the new release and all those dependencies.

**Comment by levivic** [comment]
@fbm3307 thanks for the info. As mentioned in my email reply, we have already started working with the doc team to make it clear to the clients and we will direct them to the openshift/library github repo directly once it's merged. Also due to the urgency of getting the solution delivered to customers (end of the month) and other prioritized tasks the team has, we will look at the chart based solution later, after the original template solution gets published.

**Comment by fbm3307** [comment]
Hi @levivic , Since this points to location of a personal repo, as per OCP guidelines, this PR cannot be merged.

**Comment by levivic** [comment]
@fbm3307 what the guidelines are? what kind of repo would be qualified?

**Comment by levivic** [comment]
@fbm3307 could you please merge the PR as @dale-fu already moved the original template to a public org?

**Comment by fbm3307** [comment]
@levivic done

**Pull request merged**
