### PR TITLE
Image streams 19.0 for wildfly

### PR DESCRIPTION
**Pull request by jfdenise**
New 19.0 versions for wildfly-centos7 and wildfly-runtime-centos7 imagestreams.

### CODE REVIEW

**Comment by gabemontero** [comment]
@jfchevrette did you run `make import` per https://github.com/openshift/library#running-the-script ?

There are some file changes from that command I would have expected.

**Comment by jfdenise** [comment]
Yes, I ran it. I just re-run it, no changes.

**Comment by gabemontero** [comment]
> Yes, I ran it. I just re-run it, no changes.

cool thanks ... incorrect expectations from me ... verify job passed as well

/lgmt

**Pull request merged**
