### PR TITLE
RHSSO-2648 Update RH-SSO templates & image-streams to '7.6.6.GA' rele…

### PR DESCRIPTION
**Pull request by Pepo48**
…ase/tag

* bumped the version
* synced the probe timeouts that now match the operator default behaviour

Signed-off-by: Peter Zaoral <pzaoral@redhat.com>

### CODE REVIEW

**Comment by drichtarik** [comment]
@fbm3307 Can you please have a look? This should be merged asap

**Comment by drichtarik** [comment]
@fbm3307 thanks. looks good but needs approval

**Comment by fbm3307** [comment]
I will let the tests complete and approve

**Comment by drichtarik** [comment]
Thanks!

**Comment by Pepo48** [comment]
@fbm3307 @drichtarik thanks!

**Pull request merged**
