### PR TITLE
Add Open Liberty imagestream to official imagestreams

### PR DESCRIPTION
**Pull request by brenthdaniel**
Add an imagestream for open liberty s2i to the list of official image streams.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@brenthdaniel thanks for your PR! We're happy to have OpenLiberty join the family of imagestreams available on OpenShift.

Per our [guidelines](https://github.com/openshift/library#official), `official` is only reserved for images provided and supported by Red Hat. Please update the PR to file the imagestream under the `community` group and we'll be glad to add it in.

**Comment by adambkaplan** [comment]
/hold

For move to `community`

**Comment by brenthdaniel** [comment]
Hi, 
  I chose "official" based on the fact that RH will be supporting  Open Liberty (at least on a first level basis). I'm not sure of the implications of "official" vs "community". If we deliver to community now, would we be able to move it when the support statement gets finalized?

**Comment by bparees** [comment]
> If we deliver to community now, would we be able to move it when the support statement gets finalized?

yes, moving it is no problem.

the distinction for us is "if a customer contacts us with a problem with this image/imagestream, is there a team at redhat dedicated to supporting that customer and providing a fix".

**Comment by brenthdaniel** [comment]
Thanks, I updated the PR to move it to community.

**Comment by brenthdaniel** [comment]
@bparees Is there anything else that needs to be done here prior to merging?

**Pull request merged**
