### PR TITLE
[KIECLOUD-586] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for 7.13.0 release

Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by fbm3307** [comment]
Hi @spolti I would like to suggest that instead of creating templates in openshift/library, you can create helm charts for the same (See here https://github.com/openshift-helm-charts/charts )
It is easier to create helm charts and also the helm charts would be available across ocp version 4.8 to latest 4.11. In this you will not have to worry about backporting or waiting for the release, also no worries on checking if compatible with the new release and all those dependencies.

**Comment by spolti** [comment]
Hi @fbm3307 we do not maintain these templates anymore, we still have it because we have a few customers that are still using it on ocp 3.11 and have no plans to create helm charts for it, but, this repo is for ocp 4.x, right? If so I'll close it. :)

**Comment by fbm3307** [comment]
Hi @spolti yes, and can these be removed if they are not supported in 4.x ? if yes can you raise a PR for the same?

**Comment by spolti** [comment]
@fbm3307 thanks for confirming, about the previous versions, do we really need to remove it or do you mean just remove it from the official.yaml file?

**Comment by fbm3307** [comment]
@spolti we need to remove all of it from jsons.. and also remove it from library.( whichever are no longer supported)

**Pull request closed without merging**
