### PR TITLE
Migrate apps/* into apps/v1 before the old apis get dropped

### PR DESCRIPTION
**Pull request by tnozicka**
apps/v1beta* apis are going away soon (next release)

@openshift/sig-developer-experience do we have any other repo with examples like that or is this all?

xref: https://jira.coreos.com/browse/WRKLDS-16

### CODE REVIEW

**Comment by tnozicka** [comment]
I am confused by https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_library/193/pull-ci-openshift-library-master-verify/46

is this just a cache we can't make patches to?

**Comment by adambkaplan** [comment]
/close

@tnozicka These imagestreams and templates are synced from upstream repos. We'll have to open PRs against each repo we are pulling the imagestream and template data from. 🙁

**Comment by adambkaplan** [comment]
@tnozicka we have a nightly job that syncs the data from the upstream repos. The verify script ensures that new imagestreams and templates work with this job.

**Pull request closed without merging**
