### PR TITLE
[KIECLOUD-292] - Update RHPAM and RHMD templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.4.1

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by gabemontero** [comment]
the `verify` tests says that `make import` needs to be run:  https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_library/184/pull-ci-openshift-library-master-verify/15#0:build-log.txt%3A5886

**Comment by spolti** [comment]
I run import_content script, shouldn't have the same result?

**Comment by spolti** [comment]
Hi, can this PR be merged?

**Comment by spolti** [comment]
looks like the SSO guys are actively updating the templates, yesterday this same test has passed.

**Comment by spolti** [comment]
@gabemontero can you please help to understand what is happening in this case?
The test reported changes, bu I just run make import and verify and no problems were reported:

`Diffing current official directory against freshly generated official directory
SUCCESS: Generated official directory up to date.
Diffing current community directory against freshly generated community directory
SUCCESS: Generated community directory up to date.
✔ /data/dev/sources/library [KIECLOUD-292 L|…5] 
`

**Comment by coreydaley** [comment]
@spolti You need to commit the results of whatever changes make import pulls in.  Can you try running git status or git diff and see if there are any changes that need to be committed?

**Comment by coreydaley** [comment]
Side Note: Interesting that the Travis make verify succeeded...

**Comment by spolti** [comment]
@coreydaley I did this, but now I am trying different, reset my branch to head, rebase and re-import, let's see how it goes now.

**Pull request merged**
