### PR TITLE
[RHDM-354] - Add RHDM 7.0 GA templates and image streams to Openshift…

### PR DESCRIPTION
**Pull request by spolti**
… service catalog

### CODE REVIEW

**Comment by spolti** [comment]
@luciddreamz @sspeiche can you please review?

**Comment by spolti** [comment]
Hi, looks like there is a issue in the CI:
```
\ No newline at end of file
FAILURE: Generated official directory out of date. Please run import_content.py
make: *** [verify] Error 1
```

I executed this command locally and the resources were imported, this issue is something I need to fix in my side or it is something that you need to do?

Thanks.

**Comment by coreydaley** [comment]
You need to run the import_content.py script and then commit the changes.
https://github.com/openshift/library/blob/master/README.md#adding-your-template-or-imagestream

**Comment by spolti** [comment]
@coreydaley thanks, I Just updated the PR

**Comment by bparees** [comment]
@sspeiche bump

**Comment by sspeiche** [comment]
@spolti Have these been tested/validated on both starter and pro clusters? or similar configurations. I'm not seeing on @rettori 's list of approved and tested ones.

**Comment by spolti** [comment]
@sspeiche I tested the templates on a employee instance, I don't have access to pro clusters.
I just update one template to target only pro clusters because looks like the starter only have 1gb of memory.

**Comment by sspeiche** [comment]
+1 fine by me

@rettori can weigh in if but I'd say....onwards!

**Pull request merged**
