### PR TITLE
Remove golang imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by gabemontero** [comment]
As @siamaksade added this back with https://github.com/openshift/library/pull/174 I need him as the PM in this space to sign off on the removal of the golang imagestreams, in particular the official version

@siamaksade - do you need @yselkowitz to elaborate on the removal?  I'm guessing these images are not multi arch aware, but maybe there are other pain points or directives leading to the removal I'm unaware of.

/assign @siamaksade 
/assign @gabemontero

**Comment by yselkowitz** [comment]
They are multi-arch aware, but they're going end of life next month, as announced on their pages in the catalog:

https://catalog.redhat.com/software/containers/devtools/go-toolset-rhel7/5c4fc4b8bed8bd162b6dbedc
https://catalog.redhat.com/software/containers/ubi7/go-toolset/5ce879bcd70cc57c44b49684
https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666
https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1

**Comment by gabemontero** [comment]
> They are multi-arch aware, but they're going end of life next month, as announced on their pages in the catalog:
> 
> https://catalog.redhat.com/software/containers/devtools/go-toolset-rhel7/5c4fc4b8bed8bd162b6dbedc
> https://catalog.redhat.com/software/containers/ubi7/go-toolset/5ce879bcd70cc57c44b49684
> https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666
> https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1

OK thanks for the clarification @yselkowitz 

If I read those pages correctly, rather than a new version of the image, they are telling you to install the tool set via RPM.

Hence why there is not a bump to a newer image.

that sound correct ?

If this is what is going on, I don't think we need @siamaksade 

I'll 

/lgtm

and short term 

/hold 

in case I've misread things and am confused ... feel free to unhold @yselkowitz if I read things correctly.

**Comment by yselkowitz** [comment]
You understand correctly, they are going away entirely.
/hold cancel

**Pull request merged**
