### PR TITLE
add jenkins agent imagestreams

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @bparees 

and help ... nothing got added under the operator folder ... what makes that happen ?

### CODE REVIEW

**Comment by gabemontero** [comment]
manually running https://ci.openshift.redhat.com/jenkins/view/All/job/update_openshift_library/ after this merges?

**Comment by gabemontero** [comment]
yep found it in there:

```
python ./import_content.py --match-all-tags okd,arch_x86_64 -d operator/okd-x86_64
python ./import_content.py --match-all-tags ocp,arch_x86_64 -d operator/ocp-x86_64
```

I'll try that manually

**Comment by bparees** [comment]
@gabemontero the import jenkins job re-imports all the content into various directories, so it should get populated after we merge this and run the import job:

```
python ./import_content.py --match-all-tags okd,arch_x86_64 -d operator/okd-x86_64
python ./import_content.py --match-all-tags ocp,arch_x86_64 -d operator/ocp-x86_64
python ./import_content.py --match-all-tags ocp,arch_ppc64le -d operator/ocp-ppc64le
```

**Comment by gabemontero** [comment]
couldn't wait and did it before seeing you update ... got the okd/ocp x86 already in there

**Pull request merged**
