### PR TITLE
KEYCLOAK-16291 Update openshift/library with RH-SSO 7.4.5.GA templates

### PR DESCRIPTION
**Pull request by drichtarik**
[KEYCLOAK-16291] Update RH-SSO imagestreams & templates to v7.4.5.GA release.

@gabemontero can you please have a look?

### CODE REVIEW

**Comment by gabemontero** [comment]
/lgtm cancel

saw this in the verify logs @drichtarik 

`FAILURE: official directory out of date. Please run make import`

missed that in my review  ... please to that, push the update, and we'll retest again

**Comment by drichtarik** [comment]
@gabemontero thank you. I'll update it soon

**Comment by drichtarik** [comment]
@gabemontero I have the same issue on master. With or without my commit.

**Comment by gabemontero** [comment]
> @gabemontero I have the same issue on master. With or without my commit.

ok ... thanks @drichtarik .... perhaps our periodic job had a hiccup and broke something;  we'll have to take a look later today.

@adambkaplan @coreydaley FYI

**Comment by coreydaley** [comment]
It looks like there are a few files missing on github, we may need a separate PR to clean those up first

```
E0208 09:34:28.257583 3193465 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-fuse/application-templates/GA/fuse-apicurito.yml: 404
E0208 09:34:28.297267 3193465 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-fuse/application-templates/GA/fuse-apicurito.yml: 404
E0208 09:34:28.303753 3193465 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-fuse/application-templates/GA/fuse-apicurito.yml: 404
E0208 09:34:28.608088 3193465 import.go:316] [Config: 0, Doc: official] unable to fetch template url "https://raw.githubusercontent.com/jboss-fuse/application-templates/GA/quickstarts/spring-boot-camel-rest-3scale-template.json": 404
E0208 09:34:28.728417 3193465 import.go:316] [Config: 0, Doc: official] unable to fetch template url "https://raw.githubusercontent.com/jboss-fuse/application-templates/GA/quickstarts/spring-boot-camel-template.json": 404
E0208 09:34:28.728679 3193465 import.go:316] [Config: 0, Doc: official] unable to fetch template url "https://raw.githubusercontent.com/jboss-fuse/application-templates/GA/quickstarts/spring-boot-camel-xml-template.json": 404

```

**Comment by coreydaley** [comment]
Submitted https://github.com/openshift/library/pull/269 which should unblock this.
You might have to rebase this pull request after that one merges, I'm not 100% sure on that though.

**Comment by drichtarik** [comment]
@coreydaley rebased

**Comment by gabemontero** [comment]
> Submitted #269 which should unblock this.
> You might have to rebase this pull request after that one merges, I'm not 100% sure on that though.

thanks @coreydaley 

/lgtm

**Comment by drichtarik** [comment]
interestingly, after updating my master and running make verify, I still have the same error on my local machine.
Again with or without my commit.
git reset HEAD --hard
git pull upstream master
make verify (fail)
make build
make import
make verify (fail)

Same with my rebased branch.

**Comment by gabemontero** [comment]
> interestingly, after updating my master and running make verify, I still have the same error on my local machine.
> Again with or without my commit.
> git reset HEAD --hard
> git pull upstream master
> make verify (fail)
> make build
> make import
> make verify (fail)
> 
> Same with my rebased branch.

We need to monitor the periodic I think so that it does what it is suppose to do, then if you rebase I think it will work @drichtarik 

Both @coreydaley and I have a meeting now but we will look at it more later today our time ... sorry for the churn / thanks

**Comment by drichtarik** [comment]
@gabemontero this PR has already been rebased. I quickly checked again. Source branch has 858 commits and target master branch has 857.

**Comment by gabemontero** [comment]
/hold

while myself and @coreydaley sort out what is still wrong

**Comment by gabemontero** [comment]
the periodic job ran https://github.com/openshift/library/commit/1f9171749316b8d637159b3ca747182039c4dd1f and still see failure

**Comment by gabemontero** [comment]
Ok I've checked out master branch and make verify / make import work for me

I'll next check out @drichtarik 's PR locally and see what I can make out from these 
```
\ No newline at end of file
FAILURE: official directory out of date. Please run make import
```

**Comment by gabemontero** [comment]
with that master branch attempt I am at 

```
$ git log -1
commit 1f9171749316b8d637159b3ca747182039c4dd1f (HEAD -> manual-import, upstream/master, origin/master, origin/HEAD, master)
Author: ci-robot <ci-robot@k8s.io>
Date:   Mon Feb 8 15:05:56 2021 +0000

    Automatic importer job update
```

**Comment by coreydaley** [comment]
I see that tag 7.4.5.GA is referenced in the PR, but there is no tag with that name, so the url can not be found:
https://github.com/jboss-container-images/redhat-sso-7-openshift-image/tags

**Comment by gabemontero** [comment]
OK, here is what I see @drichtarik after checking out this PR via 

```
git fetch upstream pull/268/head:local-upstream-268-copy
git checkout local-upstream-268-copy
```

The branch was still missing the commit from our periodic 

```
(local-upstream-268-copy)$ git log -3
commit b4d2ebef25922e7e4242f68dc25a2fde4f386f36 (HEAD -> local-upstream-268-copy)
Author: Denis Richtarik <drichtar@redhat.com>
Date:   Thu Feb 4 11:46:02 2021 +0100

    KEYCLOAK-16291 Update openshift/library with RH-SSO 7.4.5.GA templates

commit 1f9171749316b8d637159b3ca747182039c4dd1f (upstream/master, origin/master, origin/HEAD, master, manual-import)
Author: ci-robot <ci-robot@k8s.io>
Date:   Mon Feb 8 15:05:56 2021 +0000

    Automatic importer job update

commit ef351c1086b91fd182d1117396106b53e99ca4d6
Merge: a043415 e1d43df
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Mon Feb 8 10:04:20 2021 -0500

    Merge pull request #269 from coreydaley/fix_missing_urls
    
    fix missing urls
```

So I rebased it in

```
git rebase master
```

And then see 

```
(local-upstream-268-copy)$ git log -4
commit b4d2ebef25922e7e4242f68dc25a2fde4f386f36 (HEAD -> local-upstream-268-copy)
Author: Denis Richtarik <drichtar@redhat.com>
Date:   Thu Feb 4 11:46:02 2021 +0100

    KEYCLOAK-16291 Update openshift/library with RH-SSO 7.4.5.GA templates

commit 1f9171749316b8d637159b3ca747182039c4dd1f (upstream/master, origin/master, origin/HEAD, master, manual-import)
Author: ci-robot <ci-robot@k8s.io>
Date:   Mon Feb 8 15:05:56 2021 +0000

    Automatic importer job update

commit ef351c1086b91fd182d1117396106b53e99ca4d6
Merge: a043415 e1d43df
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Mon Feb 8 10:04:20 2021 -0500

    Merge pull request #269 from coreydaley/fix_missing_urls
    
    fix missing urls

commit e1d43dfe90b23b767b6de11d33d23276992908be
Author: Corey Daley <cdaley@redhat.com>
Date:   Mon Feb 8 09:45:13 2021 -0500

    fix missing urls
```

We no longer get the SSO errors that @coreydaley fixed, but I see error logs on the `make import` around the missing tag he just mentioned:

```
E0208 11:56:58.840071   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.854911   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.855587   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.856839   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.856957   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.857531   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.857715   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.858009   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.862015   18963 common.go:99] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-image-stream.json: 404
E0208 11:56:58.862057   18963 common.go:99] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-image-stream.json: 404
E0208 11:56:58.862307   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
E0208 11:56:58.879428   18963 common.go:110] unable to fetch url during preload https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.4.5.GA/templates/openj9/sso74-openj9-ocp4-x509-postgresql-persistent.json: 404
```

try rebasing again into your branch to pick up 1f9171749316b8d637159b3ca747182039c4dd1f and then sort out what is up with v7.4.5.GA

**Comment by gabemontero** [comment]
to get my master branch up to date, I did 

```
# switch to the remote, default branch
git checkout master
# pull from the orig repo you forked from ...i.e. openshift
git fetch upstream
git fetch upstream --tags
# get everybody else's changes in the remote repo to your local copy
git rebase upstream/master
# get those changes to your remote fork on github
git push origin master #  --force
git push origin --tags
```

**Comment by drichtarik** [comment]
@coreydaley Thanks for pointing out that missing tag. It's been tagged. @gabemontero I believe the blocks of terminal outputs are the same. What did I miss? The rebase seems to be on top of the latest commit.

**Comment by drichtarik** [comment]
It seems to be healthy now

**Pull request merged**
