### PR TITLE
[NODE-518] Move modern-webapp from official to community

### PR DESCRIPTION
**Pull request by yselkowitz**
Filing on behalf of @lholmquist.

### CODE REVIEW

**Comment by gabemontero** [comment]
@yselkowitz is `[NODE-518]` by chance reference to a Jira somewhere ?  And perhaps that explains the reasoning for the change ?

thanks

**Comment by lholmquist** [comment]
The web-app image that was being used, was only a tech preview and is now being deprecated.  So that is why it needs to be removed from the official listing.  It is being replaced with a community only image

**Comment by gabemontero** [comment]
thanks for the explanation

/lgtm

**Comment by gabemontero** [comment]
ah ... the new 4.4 post feature freeze need a bugzilla requirement is hitting openshift/library as well.

I'll see if that is easy to turn off / something we would want to do and report back.

**Comment by gabemontero** [comment]
@adambkaplan is trying to remove the bz requirement here via https://github.com/openshift/release/pull/7035

**Pull request merged**
