### PR TITLE
Bug 1871280: checking for the existence of the actual document before deciding if we need to remove it

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by gabemontero** [comment]
@yselkowitz FYI

/lgtm

thanks @coreydaley !

**Comment by gabemontero** [comment]
if the delete does not happen with your next PR @yselkowitz let's get the output from your make's to @coreydaley

**Comment by gabemontero** [comment]
weird verify was green @coreydaley per https://prow.ci.openshift.org/pr-history/?org=openshift&repo=library&pr=244

but now it is complaining about `FAILURE: official directory out of date. Please run make import`

**Comment by coreydaley** [comment]
@gabemontero just did a make import and pushed it, something must have changed somewhere.

**Comment by gabemontero** [comment]
/lgtm

more changes are in flight as well @coreydaley but let's see how the timing with  everything works

**Pull request merged**
