### PR TITLE
remove broken infinispan content

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@slaskawi  you guys appear to have removed this content from the upstream repo, so i'm removing it from library as it is now breaking our import process.

**Comment by galderz** [comment]
@bparees That was me, sorry about that. Didn't realise about the link. I'll submit a PR with the new templates :)

**Comment by bparees** [comment]
@galderz np, thanks in advance.

**Comment by galderz** [comment]
@bparees #137

**Comment by galderz** [comment]
https://github.com/openshift/library/pull/137

**Pull request merged**
