### PR TITLE
Add templates and imagestreams for EAP 7.4

### PR DESCRIPTION
**Pull request by jmesnil**
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
@luck3y fiy

**Comment by gabemontero** [comment]
you need to run `make import` and add those changes to your commit @jmesnil 

at least that is what the verify failure things

**Comment by jmesnil** [comment]
@gabemontero sorry, I did not `git add` the files 😢 I've amended the commits and retriggered the tests

**Comment by gabemontero** [comment]
looks good now thanks @jmesnil 

/lgtm

**Pull request merged**
