### PR TITLE
EAP / EAP CD template updates

### PR DESCRIPTION
**Pull request by luck3y**
- Add EAP CD basic template to OSO starter
 - EAP template / imagestreams to ose-v1.4.15

### CODE REVIEW

**Comment by luck3y** [comment]
Note: this adds a template to OSO Start - eap-cd-basic-s2i.json.

The EAP CD imagestreams reference the new container registry, but while testing by manually importing the imagestream into OSO starter I was unable to get the image to pull from registry.redhat.io.

Will this registry work on OSO Starter?

cc: @bparees

**Comment by dak1n1** [comment]
It's not an issue for Online. We'll be able to use the new registry as of Sept 18th in Pro tier. It will be ready sooner in Starter (next week). In the mean time, it's fine to merge new imagestreams to both openshift/library and openshift/online. I did a sync from openshift/library yesterday that pulled in all the latest imagestreams referencing registry.redhat.io. Those are now installed in INT.

**Comment by bparees** [comment]
thanks @dak1n1 

i'm going to proactively merge this and if @luciddreamz has concerns about the template being added to starter we can go back and remove the tag.

**Comment by luck3y** [comment]
@bparees Great, thanks Ben. @luciddreamz Please reach out to me via email (kwills@redhat.com) if you need more info on this change.

**Pull request merged**
