### PR TITLE
[CLOUD-1241] - Include RHPAM templates in OpenShift release

### PR DESCRIPTION
**Pull request by spolti**
Signed-off-by: Filippe Spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by spolti** [comment]
Hi, is this PR ready to get merged or do I need to do something else?

**Comment by bparees** [comment]
it's ready, i was waiting to see if @luciddreamz had any comments but i'll merge.

**Comment by spolti** [comment]
@bparees no worries, thanks :)

**Pull request merged**
