### PR TITLE
KIECLOUD-584-Update RHPAM and RHDM templates and imagestreams on Open…

### PR DESCRIPTION
**Pull request by msmagnanijr**
…Shift Service Catalog for 7.12.0 release

Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

### CODE REVIEW

**Review by desmax74 — APPROVED** [review]

**Comment by msmagnanijr** [comment]
@coreydaley @dperaza4dustbit could you please take a look? thanks

**Comment by spolti** [comment]
@vrutkovs can you please take a look on this one?

**Pull request merged**
