### PR TITLE
s2i-dotnetcore: the upstream repo renamed the branch from master to main.

### PR DESCRIPTION
**Pull request by tmds**
Also updates the community.yaml file to use the regular dotnet_imagestreams.json. This json file defines UBI based images. There are no separate CentOS images.

@yselkowitz ptal.

### CODE REVIEW

**Comment by yselkowitz** [comment]
@tmds you need to run `make import` and include the changes therefrom in this PR.

**Comment by tmds** [comment]
@yselkowitz done, I've also removed `suffix: centos` in `community.yaml`.

**Pull request merged**
