### PR TITLE
[RHSSO-2426] Update RH-SSO templates & image-streams to 'v7.6.3.GA' release / tag

### PR DESCRIPTION
**Pull request by iankko**
[RHSSO-2426] Update RH-SSO templates & image-streams to 'v7.6.3.GA'
    release / tag. Relevant erratum is: RHSA-2023:2710
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

### CODE REVIEW

**Comment by iankko** [comment]
@fbm3307 Hello Feny, could you possibly have a look at this one once got a chance?

(@pskopek jfyi -^)

Thanks!
Jan

**Comment by fbm3307** [comment]
@iankko , The Samples operator is for OCP4.8+
How will the OCP3.x imagestreams be useful in that.? I do not think any customer to be using ocp3.x if they are using 4.x versions

**Comment by iankko** [comment]
> @iankko , The Samples operator is for OCP4.8+ How will the OCP3.x imagestreams be useful in that.? I do not think any customer to be using ocp3.x if they are using 4.x versions

@fbm3307 Right, great catch with the `*-ocp3-*` templates. Will remove them yet. Do you know / can you hint a repo, where those OCP / OpenShift 3.X related updates should go?

AFAICT, previously there existed an OpenShift 3.X targeting / dedicated examples repository, so PRs like this one:
* https://github.com/openshift/openshift-ansible/pull/8902
to update the OCP 3.X templates & imagestreams for a particular product was possible.

Is there something like this repo there yet still? 

@bparees -^ Hey Ben, maybe you can hint into which repo the updated RH-SSO templates targeting OCP-3.X clusters (AFAIU it's still supported version) should go?

Thanks,
Jan

**Comment by bparees** [comment]
> @bparees -^ Hey Ben, maybe you can hint into which repo the updated RH-SSO templates targeting OCP-3.X clusters (AFAIU it's still supported version) should go?

did we ship them with 3.11?  if we did i'd expect to see them here and this is where they'd need to be updated:

https://github.com/openshift/origin/tree/release-3.11/examples

but i really wouldn't expect us to be updating 3.11 for this sort of thing at this point, even if they did ship with it.

**Pull request merged**
