### PR TITLE
Update postgresql imagestreams filenames

### PR DESCRIPTION
**Pull request by yselkowitz**
Also, fixup automatic import job after previous merge.

/assign @gabemontero

### CODE REVIEW

**Comment by gabemontero** [comment]
> Also, fixup automatic import job after previous merge.

the `library/operator` path is even more critical than the `library/arch` path 

based on cross referencing some of your prior PRs @yselkowitz I *think* your arch removals have resulted in 
stuff getting cleaned out of the operator dirs

for example, when I look at https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/golang/imagestreams I no longer see the `golang-rhel7.json` file

but I'm going to double check after this PR merges and confirm that is what is going on

/lgtm
> 
> /assign @gabemontero

**Comment by gabemontero** [comment]
> > Also, fixup automatic import job after previous merge.
> 
> the `library/operator` path is even more critical than the `library/arch` path
> 
> based on cross referencing some of your prior PRs @yselkowitz I _think_ your arch removals have resulted in
> stuff getting cleaned out of the operator dirs
> 
> for example, when I look at https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/golang/imagestreams I no longer see the `golang-rhel7.json` file
> 
> but I'm going to double check after this PR merges and confirm that is what is going on

and yep they have been removed ... for example, if you look at https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/mysql/imagestreams you'll see the rhel7 file is gone now that the periodic has run
> 
> /lgtm
> 
> > /assign @gabemontero

**Comment by yselkowitz** [comment]
> the `library/operator` path is even more critical than the `library/arch` path

Understood, since that is what is synced into cluster-samples-operator.

> based on cross referencing some of your prior PRs @yselkowitz I _think_ your arch removals have resulted in
> stuff getting cleaned out of the operator dirs
> 
> for example, when I look at https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/golang/imagestreams I no longer see the `golang-rhel7.json` file

I deleted the `golang-rhel7.json` files in #241 and the `mysql-rhel7.json` files in this PR.

> but I'm going to double check after this PR merges and confirm that is what is going on

The automatic import job following this PR also did NOT remove anything:

https://github.com/openshift/library/commit/1f4d22010a5d89659dd84d8d0c5e96e10ecc20c2

https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/postgresql/imagestreams

So this still needs to be fixed in the job.

**Comment by gabemontero** [comment]
> > the `library/operator` path is even more critical than the `library/arch` path
> 
> Understood, since that is what is synced into cluster-samples-operator.
> 
> > based on cross referencing some of your prior PRs @yselkowitz I _think_ your arch removals have resulted in
> > stuff getting cleaned out of the operator dirs
> > for example, when I look at https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/golang/imagestreams I no longer see the `golang-rhel7.json` file
> 
> I deleted the `golang-rhel7.json` files in #241 and the `mysql-rhel7.json` files in this PR.
> 
> > but I'm going to double check after this PR merges and confirm that is what is going on
> 
> The automatic import job following this PR also did NOT remove anything:
> 
> [1f4d220](https://github.com/openshift/library/commit/1f4d22010a5d89659dd84d8d0c5e96e10ecc20c2)
> 
> https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official/postgresql/imagestreams
> 
> So this still needs to be fixed in the job.

Yes understood/agreed and I opened a BZ for @coreydaley to look at that as noted in that other PR

All what I was trying to say was that with the periodic as is (minus any fix from @coreydaley ) and your manual delete from the `arch` dir the final result of what gets put into the `operator` dir is what we wanted i.e. your deleted files not showing up in the operator payload

thanks

**Comment by yselkowitz** [comment]
Oh, you meant that the old ones aren't coming back.  Right, although if that was happening, something would have really been wrong.

**Pull request merged**
