### PR TITLE
Add EAP CD 14 release to official.yaml

### PR DESCRIPTION
**Pull request by luck3y**
SIgned-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by coreydaley** [comment]
@luck3y Looks like you need to run "make import" and then commit the results.

**Comment by luck3y** [comment]
Seems like this needs to be updated again, will try that.

**Comment by luck3y** [comment]
@coreydaley Thanks, I did that on the first one, but maybe something got merged in the meantime,.

**Comment by coreydaley** [comment]
@luck3y Yeah, something could have changed.

**Comment by bparees** [comment]
@luck3y looks like you need to rebase and rerun make import to make travis happy.

**Comment by luck3y** [comment]
My fault guys, forgot to git add a file :/

**Comment by bparees** [comment]
np, this is why we have tests :)

**Comment by bparees** [comment]
optimistically:
/lgtm

**Comment by luck3y** [comment]
Thanks @coreydaley and @bparees.

**Pull request merged**
