### PR TITLE
Updated JWS image streams and templates

### PR DESCRIPTION
**Pull request by bekionel**
* Update 'webserver_version' variable to ose-v1.4.17
    * Introduce 'webserver3_version' variable based at jws31-v1.4
    * Introduce 'webserver5_version' variable based at jws50-v1.2
    * Introduce updated locations of JWS 3.1 and 5.0 image streams and templates

    Signed-off-by: Sokratis Zappis <szappis@redhat.com>

### CODE REVIEW

**Comment by adambkaplan** [comment]
@bekionel sorry needs to be rebased - merged in a conflicting change to `official.yaml`

**Comment by bekionel** [comment]
@adambkaplan Thanks,  I opened https://github.com/openshift/library/pull/159 , closing this PR.

**Pull request closed without merging**
