### PR TITLE
Remove OpenShift Online Starter profile

### PR DESCRIPTION
**Pull request by yselkowitz**
Online Starter has been decommissioned, so there should be no further need for this.

### CODE REVIEW

**Comment by yselkowitz** [comment]
/cc @adambkaplan @gabemontero 
in case there was some reason this wasn't removed until now.

**Comment by gabemontero** [comment]
hey @jupierce - if I recall correctly, you were the original requestor for having online starter profile set up for the openshift samples here in this repo.  If so, do you have any issues with removing the online starter specific samples here now that online starter has been decommissioned as @yselkowitz notes?

@bparees - do you recall any precedence yay or nay for removing profiles from this repo?

thanks

**Comment by bparees** [comment]
> do you recall any precedence yay or nay for removing profiles from this repo?

no precedence, but if no one is consuming content based on that tag any more, removing it seems reasonable to me.

**Comment by jupierce** [comment]
No issues here.

**Comment by gabemontero** [comment]
thanks @jupierce @bparees 

/approve

/assign @dperaza4dustbit 

for final review after @yselkowitz rebases

**Pull request merged**
