### PR TITLE
[KIECLOUD-585] Update RHPAM and RHDM templates and imagestreams on Op…

### PR DESCRIPTION
**Pull request by davidesalerno**
…enShift Service Catalog for 7.12.1 release

Signed-off-by: Davide Salerno <dsalerno@redhat.com>

See: https://issues.redhat.com/browse/KIECLOUD-585

### CODE REVIEW

**Comment by gabemontero** [comment]
@davidesalerno you crated this as a draft PR, and hence it has the WIP label.

We will wait on LGTM'ing until you sort that out (maybe you have more changes coming?)

**Comment by davidesalerno** [comment]
@gabemontero The PR now is ready for review

**Pull request merged**
