### PR TITLE
adding ruby ppc64le imagestream

### PR DESCRIPTION
**Pull request by jeffdyoung**
@bparees I believe this is the format we agreed on. The json link will be valid after this PR is approved:
https://github.com/sclorg/s2i-ruby-container/pull/188

If this looks good, I'll submit PRs for the other imagestreams.

### CODE REVIEW

**Comment by jeffdyoung** [comment]
nvm.. I didn't use the right tag.. fixing

**Comment by bparees** [comment]
this is going to fail until that imagestream file actually exists in the upstream repo.

**Comment by jeffdyoung** [comment]
@bparees The file exists now. All good?

**Comment by bparees** [comment]
@jeffdyoung please run make import and check in all the additional files.

**Comment by bparees** [comment]
@jeffdyoung a PR for each is going to be a bit annoying since the import verification is going to force you to keep rebasing as each one goes in.  How about a commit for each one and then a final commit for the updated import result?  (and i'll leave it un-squashed on merge)

**Comment by bparees** [comment]
@jeffdyoung i'm happy to merge this one if you think it's ready

**Comment by jeffdyoung** [comment]
@sdodson is this PR enough for you to test service catalog for ppc64le, or do you need example templates too?

**Comment by jeffdyoung** [comment]
@bparees go ahead and merge please. I'll create another one when the prs for the other imagestreams and templates are approved. Thanks

**Pull request merged**
