### PR TITLE
[KIECLOUD-418] - Update RHPAM and RHDM templates and imagestreams on …

### PR DESCRIPTION
**Pull request by spolti**
…OpenShift Service Catalog for release 7.8.1

Signed-off-by: spolti <fspolti@redhat.com>

### CODE REVIEW

**Comment by gabemontero** [comment]
@spolti am I correct in seeing that all the PHPAM/PHDM imagestream images are rhel/ubi v8 based?

For the products which still have the mixture, we have started asking for adherence to new set of naming conventions, but I think if you all are v8 only we won't need to bother.  But if I'm missing some v7 based images somewhere let me know.

@yselkowitz FYI

**Comment by yselkowitz** [comment]
They made separate imagestreams for the rhel8 based versions some time ago so I'd say it doesn't apply to them.

**Comment by spolti** [comment]
@gabemontero yes, all images are based on ubi8.

**Pull request merged**
