### PR TITLE
Update Fuse entries with 7.1 release

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by bparees** [comment]
are the imagestreams picking up the 7.1 image?

**Comment by astefanutti** [comment]
@bparees yes, it's been updated with 0ee13ae7f2c2fdcf14c3d6927568ccc8ac5ac946.

**Comment by bparees** [comment]
@astefanutti thanks. since this is a docs url change only i'll merge it w/ the broken test.  Normally we ask that people run "make import" and include the changed files to ensure their updates all successfully import and so we can see the new content that's being pulled in.

**Comment by astefanutti** [comment]
@bparees ah sorry, I forgot about it. I won't next time. Thanks.

**Pull request merged**
