### PR TITLE
Update EAP imagestreams and templates

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
Note this also includes https://github.com/openshift/library/pull/236 but is a seperate update.

**Comment by gabemontero** [comment]
You'll need to rebase with #236 merging @luck3y and re-run `make import` per the results in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_library/237/pull-ci-openshift-library-master-verify/1290309398618443776

**Comment by luck3y** [comment]
@gabemontero Thanks Gabe, done.

**Pull request merged**
