### PR TITLE
Update amq63 version to 1.4.16

### PR DESCRIPTION
**Pull request by gaohoward**
Signed-off-by: Howard Gao <howard.gao@gmail.com>

### CODE REVIEW

**Comment by bparees** [comment]
this change appears to have been applied incorrectly.

you should update official.yaml, then run "make import", then check in all changed files.

Also while testing the change locally I hit this error:
```
Error      | Not Found         | https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.16/amq/amq62-image-stream.json
```

amq62 needs to be restored upstream, we don't remove imagestreams.

**Comment by gaohoward** [comment]
Thanks @bparees, I'll update my PR.

**Comment by gaohoward** [comment]
Hi @bparees, the amq62 stuff was removed according to the deprecation task
https://issues.jboss.org/browse/CLOUD-2593
Should I revert all the changes made for this jira (library and template)?

Thanks
Howard

**Comment by gaohoward** [comment]
Hi @bparees,

I submitted a PR to restore amq62 image streams in application template.
https://github.com/jboss-openshift/application-templates/pull/483
I think that's the reason why import fails.
Can you review the PR?

Thanks
Howard

**Comment by gaohoward** [comment]
@bparees It looks like this depends on a new tag from application-templates repo. I'll start once the new tag is made (next week).

**Comment by bparees** [comment]
@gaohoward still coming back to this?

**Comment by gaohoward** [comment]
@bparees Hi Ben,
This PR is blocked because it depends on a new tag from application-template (which will include the missing amq62 stuff). I'll update this PR once the new tag is out (supposedly 1.4.17)

Howard

**Comment by yvon7** [comment]
Great

**Comment by coreydaley** [comment]
/close
No activity for 2 years

**Pull request closed without merging**
