### PR TITLE
Removing v1 duplicate from apiVersion of cakephp-mysql

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
Signed-off-by: David Peraza <dperaza@redhat.com>

### CODE REVIEW

**Comment by yselkowitz** [comment]
Nack.  This needs to be fixed in the source in https://github.com/sclorg/cakephp-ex.git and it will be synced here automatically.

But how did that get through CI?!?

**Comment by gabemontero** [comment]
sorry @dperaza4dustbit missed that you already opened https://github.com/sclorg/cakephp-ex/pull/131 for SCL

yeah let's just close this PR, pester them to merge ^^ and at worst keep a list of patches you have to carry ... at least that is my suggestion

**Comment by gabemontero** [comment]
with https://github.com/sclorg/cakephp-ex/pull/131 merginge and this repo's auto import https://github.com/openshift/library/commit/5bdef328535e4121c051a653fc8d47c177944237 of that merge, we can officially

/close

**Pull request closed without merging**
