### PR TITLE
community.yaml: Update sources to C9S/UBI9

### PR DESCRIPTION
**Pull request by LorbusChris**
Removes stale and deprecated sources

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Comment by fbm3307** [comment]
Taking a look at this PR

**Comment by LorbusChris** [comment]
Note that the only manual change here was to `community.yaml` - the rest of the changes is generated from that.

**Comment by fbm3307** [comment]
@LorbusChris yes , but i do need to make sure it doesn't interfere with Cluster Samples operator, as CSO is currently being downsized and hence the delay.

**Comment by LorbusChris** [comment]
There are further PRs which will affect what gets pulled into OpenShift:
- https://github.com/sclorg/httpd-container/pull/191
- https://github.com/sclorg/mariadb-container/pull/216
- https://github.com/sclorg/mysql-container/pull/349

**Comment by fbm3307** [comment]
@LorbusChris will be approving  this PR, but just FYI, that we are downsizing cluster samples operator, The phase-1 of it is already in progress and by year end we will pull out the support for Non-s2i samples and then there are plans for converting S2i ones to helmcharts. so CSO will stop managing the imagestreams/templates. so if you are updating this for long term basis you might want to consider other option if these are meant for openshift.

**Comment by LorbusChris** [comment]
@fbm3307 thanks for the context. I'm not really attached to the samples operator, so all that's fine with me.

This change is mainly to get rid of references to docker.io in the samples we ship today, as those make us hit rate limits in CI.

**Comment by fbm3307** [comment]
@LorbusChris okay makes sense

**Pull request merged**
