### PR TITLE
Adding Feny's name to the owners file

### PR DESCRIPTION
**Pull request by fbm3307**
Adding Feny's name to the owners file

Signed-off-by: Feny Mehta <fbm3307@gmail.com>

### CODE REVIEW

**Comment by gabemontero** [comment]
@fbm3307 you'll need @dperaza4dustbit to help you go through the process of getting added to the openshift

/ok-to-test

**Comment by dperaza4dustbit** [comment]
> @fbm3307 you'll need @dperaza4dustbit to help you go through the process of getting added to the openshift
> 
> /ok-to-test

That will remove the do-not-merge as well once she joins and I run the verify-owners command, right?

**Pull request merged**
