### PR TITLE
update EAP 7.2 SSO template to use the correct SSO 7.3 adapters

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
I guess this would probably be auto-imported anyway, but I've opened it just to make sure its not missed.

**Comment by bparees** [comment]
> I guess this would probably be auto-imported anyway, but I've opened it just to make sure its not missed.

in theory yes, though i've seen some issues w/ our auto-importing that i haven't had time to dig into, so it's just as well you submitted this.

**Comment by luck3y** [comment]
@bparees Thanks :)

**Pull request merged**
