### PR TITLE
Openjdk update to release ref

### PR DESCRIPTION
**Pull request by jmtd**
See some discussion in https://github.com/jboss-container-images/openjdk/pull/107

### CODE REVIEW

**Comment by gabemontero** [comment]
@jmtd did you run `make verify` in your local PR branch ?

**Comment by jmtd** [comment]
@openshift-ci-robot 
> @jmtd: The following test failed, say

Investigating

@gabemontero  
> did you run make verify in your local PR branch ?

Yep…

**Comment by jmtd** [comment]
I don't know if it relates to the failure or not, but I've raised https://github.com/jboss-container-images/openjdk/pull/111 in the OpenJDK repository which, when merged, will result in changes in the streams here, so I'll force-refresh this branch when that's merged and send the bot retry command.

**Comment by gabemontero** [comment]
When I check out your PR locally and run `make verify` I get this error:

```
Diffing current official directory against freshly generated official directory
diff -Naupr official/java/imagestreams/openjdk-1.8-rhel8-rhel7.json _output/official/java/imagestreams/openjdk-1.8-rhel8-rhel7.json
--- official/java/imagestreams/openjdk-1.8-rhel8-rhel7.json	1969-12-31 19:00:00.000000000 -0500
+++ _output/official/java/imagestreams/openjdk-1.8-rhel8-rhel7.json	2020-01-20 11:06:37.779708383 -0500
@@ -0,0 +1,38 @@
+{
+    "apiVersion": "v1",
+    "kind": "ImageStream",
+    "labels": {
+        "xpaas": "1.4.17"
+    },
+    "metadata": {
+        "annotations": {
+            "openshift.io/display-name": "Red Hat OpenJDK 1.8 (RHEL8)",
+            "openshift.io/provider-display-name": "Red Hat, Inc.",
+            "version": "1.4.17"
+        },
+        "name": "openjdk-1.8-rhel8"
+    },
+    "spec": {
+        "tags": [
+            {
+                "annotations": {
+                    "description": "Build and run Java applications using Maven and OpenJDK 1.8 upon RHEL8.",
+                    "iconClass": "icon-rh-openjdk",
+                    "openshift.io/display-name": "Red Hat OpenJDK 1.8 (RHEL8)",
+                    "sampleContextDir": "undertow-servlet",
+                    "sampleRepo": "https://github.com/jboss-openshift/openshift-quickstarts",
+                    "tags": "builder,java,openjdk,ubi8,hidden",
+                    "version": "1.0"
+                },
+                "from": {
+                    "kind": "DockerImage",
+                    "name": "registry.redhat.io/openjdk/openjdk-1.8-rhel8:1.0"
+                },
+                "name": "1.0",
+                "referencePolicy": {
+                    "type": "Local"
+                }
+            }
+        ]
+    }
+}
\ No newline at end of file
FAILURE: Generated official directory out of date. Please run make import
make: *** [Makefile:8: verify] Error 1
```

So yeah maybe related to what you noted

**Comment by gabemontero** [comment]
/hold

until presumably https://github.com/jboss-container-images/openjdk/pull/111 merges

**Comment by gabemontero** [comment]
and a re-run of `make import` and `make verify` occur afterward

**Comment by jmtd** [comment]
> When I check out your PR locally and run make verify I get this error:

Bizarre that I cannot reproduce. Although in my clone I note this file is generated but an untracked file: official/java/imagestreams/openjdk-1.8-rhel8-rhel7.json

I'm going to try a clean clone, venv etc. to re-run verify after having merged https://github.com/jboss-container-images/openjdk/pull/111

**Comment by jmtd** [comment]
/assign @gabemontero

Hi @gabemontero can you take another look at this one now, please?

**Comment by gabemontero** [comment]
/hold cancel

/lgtm

thanks @jmtd !!

**Pull request merged**
