### PR TITLE
WIP: bump xpaas_version to ose-v1.4.7

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

v1.4.7 should release next week

### CODE REVIEW

**Comment by bparees** [comment]
can you run the import script("make import") and include the updates in this PR?

**Comment by bparees** [comment]
@dinhxuanvu fyi/ptal too

**Comment by rcernich** [comment]
ok, not sure if i did the right thing or not.  hopefully, ``make import`` was all that was required.

**Comment by dinhxuanvu** [comment]
I thought this is gonna be an upgrade from 1.4.x to 1.4.7 but some of templates is downgrading from 1.5.0 to 1.4.7. Is that right? @rcernich

**Comment by bparees** [comment]
@rcernich well it's passing travis now, so you probably did it right :)

**Comment by bparees** [comment]
not sure why we ever had "1.5.0" stuff in here, there's never been a 1.5.0 xpaas release.

**Comment by rcernich** [comment]
There's no reversion.  The version update was just to make it consistent with the tag in application-templates.  The previous should have been 1.4.5 instead of 1.5.0.  Thanks for noticing. ;)

**Comment by bparees** [comment]
thanks @rcernich !

**Pull request merged**
