### PR TITLE
Updating 3scale template location and tags

### PR DESCRIPTION
**Pull request by maneta**
In this PR we want to update the productized template of 3cale and its tags.

### CODE REVIEW

**Comment by bparees** [comment]
@dinhxuanvu @abhgupta do you guys want these templates added to online/starter as is being done here?

@maneta please run the import command and include the changes w/ your pr, as described in the readme:
https://github.com/openshift/library#adding-your-template-or-imagestream

**Comment by maneta** [comment]
@bparees ok @bparees will do! Thanks.

**Comment by dinhxuanvu** [comment]
I'm not aware of Online team adding 3scale template. So please remove the tags in the PR.

**Comment by dinhxuanvu** [comment]
Never mind my previous comment. It appears now teams can add their templates/IS to online on their own. So this PR is fine.

**Comment by bparees** [comment]
@dinhxuanvu who's vetting that they work?

**Comment by dinhxuanvu** [comment]
@bparees The templates/IS will be imported into online repo after the PR is merged. Then, we will deploy them in INT/STG and QE-testing it before they are released into PROD.

**Comment by dinhxuanvu** [comment]
@bparees Let hold on this PR for a bit longer so I can straight some details out with my team. I'm a bit new to this "open-for-all" policy.

**Comment by rettori** [comment]
@bparees, each team submitting a PR is responsible for the quality of what they submit.

**Comment by rettori** [comment]
@dinhxuanvu, please let me know of any blockers other than technical.

**Comment by bparees** [comment]
> @bparees, each team submitting a PR is responsible for the quality of what they submit.

okey dokey.  as long as no one is going to come to me when templates in online don't successfully deploy.

**Comment by dinhxuanvu** [comment]
@bparees @rettori Sounds good to me. Ready for merge.

**Comment by bparees** [comment]
@dinhxuanvu still waiting on @maneta to update the PR w/ the results of the import.

**Comment by maneta** [comment]
hey guys, I have everything in place but when I'm running `make import` I get the bellow error:

```bash
Fetching   | data              | https://raw.githubusercontent.com/jboss-fuse/application-templates/master/quickstarts/karaf2-camel-amq-template.json
Error      | Not Found         | https://raw.githubusercontent.com/jboss-fuse/application-templates/master/quickstarts/karaf2-camel-amq-template.json
```

So the Karaf2 template is broken, how should I proceed in this case?

**Comment by coreydaley** [comment]
@maneta It looks like it was renamed to 
https://raw.githubusercontent.com/jboss-fuse/application-templates/master/quickstarts/karaf-camel-amq-template.json

You should be able to just update the url.

**Comment by maneta** [comment]
yes (https://github.com/jboss-fuse/application-templates/commit/6bba0dc5d1012ed92b1358158671de1fe081a221) Ok I will do it no problem 👍 

Thanks!

**Comment by maneta** [comment]
Added little something in the Makefile. Now `make help`  and `make` shows:

```bash
verify                         Run core verification. Example: make verify
import                         Run the import script. Example: make import
dep                            Install Dependencies. Example: make dep
help                           [Default Target] - Print this help. Example: make help
```

I have introduced the `dep` target to install the dependencies

**Pull request merged**
