### PR TITLE
Restore AMQ bump

### PR DESCRIPTION
**Pull request by adambkaplan**
Restore PR #162, previously reverted.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @gabemontero 
/cc @coreydaley 

Created new PR to deal with travis issues.

**Comment by kwoodson** [comment]
@coreydaley @adambkaplan 
bump

**Comment by adambkaplan** [comment]
@kwoodson sorry - this repo got bit by an API change that Travis made. We're working on fixing our CI so we can run the verify script & get this PR merged.

**Comment by kwoodson** [comment]
@adambkaplan, any updates on the CI fix?

**Comment by adambkaplan** [comment]
ping @coreydaley @gabemontero - prow CI is working now!

**Pull request merged**
